server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  #springCloud微服务
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
#阿里云短信
aliyun:
  oss:
    endpoint: 你的endponit
    keyId: 你的阿里云keyid
    keySecret: 你的阿里云keysecret
    bucketName: srb-file
