
server:
  #服务端口
  port: 8110
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.15.128:3306/db_srb_core?useSSL=false&serverTimezone=UTC&&characterEncoding=utf8
    username: root
    password: 1234
  #环境配置
  profiles:
    active: dev
  #服务名
  application:
    name: service-core
  #redis配置
  redis:
    host: 192.168.15.128
    port: 6379
    database: 0
    password:  #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

mybatis-plus:
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置 xml 文件的路径，此处假设在 resource/xml/目录下
  #mapper-locations: classpath:xml/*.xml
#  mapper-locations:  classpath:org/example/srb/core/mapper/xml/*.xml
  mapper-locations: org/example/srb/core/mapper/xml/*.xml

##设置日志级别
#logging:
#  level:
#    #ERROR级别以及以上级别的日志输出到控制台上，其他级别将不会输出
#    root: error


